### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-pathlib2-feedstock#7]
Given the change in the name of the package from `python-pathlib2` to `pathlib2`, #2, would it make sense to rename this repository to `pathlib2-feedstock`?

**Comment by isuruf** [comment]
Yes, having this feedstock as `python-pathlib2-feedstock` can be confusing.

**Comment by ocefpaf** [comment]
Indeed. We need to figure out what would entails to rename it though. Mostly, how the feedstocks repo is populated and how robust it is to eliminate the `python-pathlib2-feedstock` and add the `pathlib2-feedstock` after renaming. In theory it should be simple, but I never looked at it.

Another approach would be to re-add this via staged-recipes with the new name and deprecate the old name (this feedstock).

**Comment by ocefpaf** [comment]
This feedstock will be removed and re-added with the `pathlib2` name once https://github.com/conda-forge/staged-recipes/pull/3554 is merged.

Ping @conda-forge/python-pathlib2

**Comment by ocefpaf** [comment]
Removing this feedstock now that https://github.com/conda-forge/staged-recipes/pull/3554 got merged.
